import ArgumentParser
import WPCore

@main
struct WP: AsyncParsableCommand {
  static let configuration = CommandConfiguration(
    commandName: "wpr",
    abstract: "wallpapers that fit your displays: rotated from folders, generated by shaders",
    groupedSubcommands: [
      CommandGroup(name: "wallpapers", subcommands: [NextCommand.self, SetCommand.self, LsCommand.self, DisplaysCommand.self, RmCommand.self]),
      CommandGroup(name: "sources", subcommands: [SourcesCommand.self, EnableCommand.self, DisableCommand.self, ScanCommand.self]),
      CommandGroup(name: "generators", subcommands: [GenCommand.self, StreamCommand.self, ModulesCommand.self, InstallCommand.self]),
      CommandGroup(name: "automation", subcommands: [TickCommand.self, TimerCommand.self]),
    ]
  )
}

extension Fill: ExpressibleByArgument {}
